<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.ResourceManager" Version="1.13.2" />
    <PackageReference Include="Azure.ResourceManager.Resources" Version="1.11.1" />
    <PackageReference Include="Azure.ResourceManager.Compute" Version="1.12.0" />
    <PackageReference Include="Azure.ResourceManager.Network" Version="1.13.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="tests\obj\tests.csproj.nuget.dgspec.json" />
    <None Remove="tests\obj\tests.csproj.nuget.g.targets" />
    <None Remove="tests\obj\tests.csproj.nuget.g.props" />
    <None Remove="tests\Azure.Tenant.Automation.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests\TagUpdateTests.cs" />
    <Compile Remove="tests\Usings.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="tags.yaml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="values.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
