name: Create Diagram
run-name: Create Repo Image Visualizer 🚀
on: 
  push:
    branches:
      - develop
      - master
jobs:
  Create-Diagram:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "images/diagram.svg"
        excluded_paths: "./.gitignore,./.github"